# Generated by Django 6.0.5 on 2026-05-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='criado', max_length=20)),
            ],
        ),
    ]
