# Generated by Django 6.0.5 on 2026-05-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0003_pedido_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSessao', models.IntegerField(verbose_name='ID Sessão')),
                ('idAssento', models.IntegerField(verbose_name='ID Assento')),
                ('codigoPR', models.CharField(max_length=100, verbose_name='Código PR')),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('validado', 'Validado'), ('cancelado', 'Cancelado')], default='criado', max_length=20, verbose_name='Status')),
                ('ingressoMeiaEntrada', models.BooleanField(default=False, verbose_name='Ingresso Meia Entrada')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='pedido.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
            },
        ),
    ]
